name: home-assistant-fork
base: core18 # the base snap is the execution environment for this snap
version: '0.103.0' 
summary: Home Assistant as a snap 
description: |
  Home assistant is an "open source home automation that puts local control and privacy first". 
  This snap intends to follow the minor releases of Home Assistant and make them installable
  as a snap. Versioning will follow the Home Assistant releases.  
icon: ./ha_fork_icon.png
grade: devel 
confinement: strict 

parts:
  home-assistant:
    plugin: python
    python-version: python3
    source: ./home-assistant
    source-branch: master
    python-packages: [setuptools, wheel]
    after: [python]
    stage:
      - -usr/bin/python3
     
  python:
    plugin: autotools
    source: https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tgz
    configflags:
      - --prefix=/usr
    build-packages:
      - build-essential
      - zlib1g-dev
      - libncurses5-dev
      - libgdbm-dev
      - libnss3-dev
      - libssl-dev
      - libreadline-dev
      - libffi-dev
      - libsqlite3-dev
      - libbz2-dev
      - libxml2-dev
      - libxmlsec1-dev
      - liblzma-dev
      - wget
      - curl
    stage-packages:
      - libgdbm5
    stage:
      - -usr/lib/python3.8/test
      - -usr/bin/pydoc3 

apps:
  hass:
    command: hass
    daemon: simple
    restart-condition: on-failure
    restart-delay: 3s
    plugs:
      - network
      - network-bind
    environment:
      PYTHONPATH: $SNAP_USER_DATA

architectures:
  - build-on: [amd64]
    run-on: [amd64, armhf]

